### ISSUE TITLE
Actual benefit of this lib?

### ISSUE THREAD

**Issue by markerikson** [evturn/redux-connect-decorator#1]
Hi.  Not wanting to be too discouraging, but I don't see any actual point for this lib.  The React-Redux `connect` function _can_ already be used as a decorator, and also allows passing an object full of action creators as the second argument to `connect` instead of an actual `mapDispatch` function.

**Comment by luchillo17** [comment]
@markerikson Didn't know that, could you elaborate how it works or an example?

**Comment by markerikson** [comment]
Sure:

```js
// you can do this:
const mapDispatch = (dispatch) => {
    return {
        addTodo : (text) => dispatch(addTodo(text)),
        toggleTodo : (index) => dispatch(toggleTodo(index))
    }
}

// Or, just do this:
const mapDispatch = {
    addTodo,
    toggleTodo
}

// and then either way:
export default connect(mapState, mapDispatch)(TodoList);
```

All it does is pass the object through `bindActionCreators` under the hood, but it's one less thing you have to worry about yourself.  I show some examples in my blog post [Idiomatic Redux: Why Use Action Creators?](http://blog.isquaredsoftware.com/2016/10/idiomatic-redux-why-use-action-creators/).

**Comment by luchillo17** [comment]
No, i meant the decorator part, i'm trying to put it to work with typescript but missing something:
![image](https://user-images.githubusercontent.com/9698639/27367552-5cc741de-5613-11e7-8337-a9f66b74bcd4.png)
See the red underline? i keep getting this kind of error:
```ts
[ts]
Unable to resolve signature of class decorator when called as an expression.
  Type 'ComponentClass<any>' is not assignable to type 'typeof SideBar'.
    Type 'Component<any, ComponentState>' is not assignable to type 'SideBar'.
      Property 'navigateTo' is missing in type 'Component<any, ComponentState>'.
```

**Comment by markerikson** [comment]
Well, that's very much a separate question - that's a TypeScript thing, not a Redux thing specifically, and I'm afraid I haven't used TypeScript myself.

**Comment by luchillo17** [comment]
Ok but it should work as i'm using it, right?

**Comment by markerikson** [comment]
Yeah, as far as just the Javascript usage of `connect()` as a decorator goes, yes, that should be valid.  

That said, the Redux team generally suggests that you _not_ use `connect` as a decorator, but rather use it as a plain function:  `export default connect(mapState, mapDispatch)(MyComponent)`.  Using it as a decorator can interfere with expected behavior of things like React PropTypes or defaultProps (they can wind up on the wrapper component instead of the plain component), and the decorator syntax in Javascript is still not yet finalized.  I do realize that decorators are more widely used in TypeScript, so your mileage may vary there.

**Comment by luchillo17** [comment]
Got it, but the decorator approach is so appealing, but for the sake of safety i'll try to stay away from it for `connect` at least.

**Comment by evturn** [comment]
@luchillo17 the only reason I made this was because I also found the approach appealing. I also find currying in JavaScript to look awkward and prefer to use partial application instead if I can.
